security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            pattern: ^/
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
#            entry_point: login
#            form_login:
#                # "login" is the name of the route created previously
#                login_path: login
#                check_path: login
            logout:
                path: app_logout
                # where to redirect after loagout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/courier, roles: ROLE_COURIER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/register-form, role: PUBLIC_ACCESS }
        - { path: ^/register, role: PUBLIC_ACCESS }
#        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/, role: PUBLIC_ACCESS }


